name: Lint and Test Charts
on: [ workflow_dispatch,pull_request ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: run-shell
        shell: bash
        env:
          CLASH_CONFIG: ${{ secrets.CLASH_CONFIG }}
      run: |
        echo "$SUPER_SECRET"


